kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: maven:3-jdk-11-slim
    pull: if-not-exists
    commands:
    - mvn clean package
  - name: test
    image: maven:3-jdk-11-slim
    pull: if-not-exists
    commands:
      - mvn test
trigger:
  branch:
    - master